### ISSUE TITLE
Agregar sonidos para Medbots y Beepsky

### ISSUE THREAD

**Issue by Foxterosa** [Foxterosa/BoH-Bay#214]
### Cambio solicitado
Se necesita agregar el sonido y el code para los Medbots y Beepsky.
Seguramente el sonido se deba importar desde Para.

#### Información útil
Es buena idea para encontrar el texto facilmente como hacer un "Find all" y poner una frase que digan los medbots para puntualmente hallar donde poner el sonido.

**Comment by AniciaBelle** [comment]
Ya esta pana
